# Generated by Django 5.1 on 2024-08-10 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 10, 9, 45, 28, 533552, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 8, 10, 9, 45, 38, 613529, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
